### ISSUE TITLE
Emprunt "toxique"

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/colors-of-the-finances#4]
http://odm-budgetaire.org/doc-schema/CommunAnnexe_xsd_Complex_Type_ATStructEmprunt.html#ATStructEmprunt_V
"Valeur F = toxique"

**Comment by MattiSG** [comment]
Documenté dans https://github.com/DavidBruant/colors-of-the-finances/blob/master/docs/format-fichier.md#annexes. Pour moi cette issue peut être fermée.

**Comment by DavidBruant** [comment]
Je gardais l'issue en prévision d'un outil qui affiche les emprunts présents dans un document budgétaire, mais la documentation est plus complète, donc je repartirai de là
