### ISSUE TITLE
Tous les emprunts ne sont pas de la collectivité elle-même

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/colors-of-the-finances#5]
http://odm-budgetaire.org/doc-schema/CommunAnnexe_xsd_Complex_Type_ATCodTypEmprunt.html#ATCodTypEmprunt_V
`09` = garanti pour un autre établissement

**Comment by MattiSG** [comment]
Documenté dans https://github.com/DavidBruant/colors-of-the-finances/blob/master/docs/format-fichier.md#annexes. Pour moi cette issue peut être fermée.

**Comment by DavidBruant** [comment]
En effet, pareil que #4
