### ISSUE TITLE
Que signifie l'invalidité des URLs ?

### ISSUE THREAD

**Issue by MattiSG** [DavidBruant/colors-of-the-finances#8]
Dans https://github.com/DavidBruant/colors-of-the-finances/blob/master/docs/format-fichier.md, il est dit :

> On peut noter qu'aucune des URL fournies n'est valide.

Cette formulation est ambiguë. Je vois qu'il y a un espace non échappé dans l'URL, mais j'hésite entre deux interprétations :

1. L'URL n'est pas une URI valide d'un point de vue syntaxique.
2. L'URL n'est pas résolvable vers un document.

S'il s'agit du cas 2, alors je ne considère pas qu'il s'agisse d'un problème dans une déclaration de XMLNS.

Je crois qu'il faudrait dans tous les cas expliciter cette phrase  :)

**Comment by DavidBruant** [comment]
Je visais plutôt "L'URL n'est pas résolvable vers un document". Le nom de domaine lui-même (`www.minefi.gouv.fr`) ne résoud par à une adresse IP.

Je soupçonne que ces adresses ont été créées au début du projet et jamais mises à jour.
